[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; std::make_unique は C++14 から。Arduinoの既定が gnu++11 の環境でも通るように上げておく
build_unflags = -std=gnu++11
build_flags = -Wall -std=gnu++17
